name: Reproducible build

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - '**'

permissions: read-all

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  check_build_reproducibility:
    name: 'Check build reproducibility'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 1
    - name: Restore Gradle cache and display toolchains
      uses: ./.github/actions/run-gradle
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        arguments: |
          --quiet \
          --no-configuration-cache # Disable configuration cache due to https://github.com/diffplug/spotless/issues/2318
    - name: Build and compare checksums
      shell: bash
      run: ./.github/scripts/checkBuildReproducibility.sh
